language: node_js

dist: trusty
sudo: false

node_js:
   - node # will use latest node

branches: # branches to watch for changes
  only:
    - master

cache: # things to cache
  directories:
    - node_modules

script: # the build step
  - npm run build:ci

deploy: # deploying the application
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change